### ISSUE TITLE
Feature Request: Keep dropdown open when crossing over adjacent dropdowns

### ISSUE THREAD

**Issue by CrashedMatrix** [istvan-ujjmeszaros/bootstrap-dropdown-hover#10]
I have a navbar that has several dropdowns next to one another. The setHideTimeout feature works great, but it would be even better if the opened menu stayed open even if you crossed over an adjacent dropdown for the time specified.

**Comment by istvan-ujjmeszaros** [comment]
The plugin is using the Bootstrap API and that just closes all the open dropdowns on its own. Maybe you can work around that by using CSS animations with some delay, but it is up to you.
