### ISSUE TITLE
Hover after ajax call

### ISSUE THREAD

**Issue by illycz** [istvan-ujjmeszaros/bootstrap-dropdown-hover#11]
Hi,
thank for your plugin. I have problem when I initialize hover functionality after ajax success call.
Hover not working. Strange is, when I leave browser tab and go back, hover working.

Thanks for any suggestion

Patrik

**Comment by rbu** [comment]
Are you on Chrome? Sounds like this could be #7.

**Comment by illycz** [comment]
Thanks for reply. Finally I removed this bootstrap functionality, so I can't test it.

**Comment by istvan-ujjmeszaros** [comment]
Hopefully was related to #7, please reopen if it is the same with the latest version.
