### ISSUE TITLE
Top level drop down doesnt work with multiple sublevels

### ISSUE THREAD

**Issue by Dcolonel6** [istvan-ujjmeszaros/bootstrap-dropdown-hover#14]
hey this is a brilliant plug in..Great work.But i have a problem when working with multiple sub menus(a dropdown inside another dropdown inside another dropdown etc)..i was working with data-toggle="dropdown" before..so i just initialliazed ur plugin as required .Did this:
 $('a [data-toggle="dropdown"]').bootstrapDropdownHover({

```
});
```

All the other dropdowns are working well but the top-level dropdown is not responding..dont know why

**Comment by gebeer** [comment]
I just ran into a similar problem.
For me dropdown on hover works only for the 1st level
Deeper levels do not work.
Initialized with `$('[data-toggle="dropdown"]').bootstrapDropdownHover({});`
Is this expected behaviour?

**Comment by Dcolonel6** [comment]
if you happen to find another plugin doing the same thing please share

**Comment by gebeer** [comment]
Currently I'm using http://kybarg.github.io/bootstrap-dropdown-hover/
But is brings some bloat and by default adds styles to elemnts. You can uncomment that in the JS, though.
I'd rather use this plugin here if we can can it to work with nested multi level dropdowns.

**Comment by istvan-ujjmeszaros** [comment]
My goal with the plugin was just to provide a clean and reliable way to support mouse hover with the Bootstrap javascript API. Bootstrap itself doesn't support nested dropdowns, and it would be a lot of overhead to add support for them (and I am not a fan of nested menus so I am not interested in doing it).
