### ISSUE TITLE
jquery 1.9.1

### ISSUE THREAD

**Issue by 3d-illusions** [istvan-ujjmeszaros/bootstrap-dropdown-hover#15]
Seem to be broken in jquery 1.9.1

Error:

jquery-1.9.1.min.js:4 Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover

**Comment by 3d-illusions** [comment]
fixed it

just needed to change it to:

```
  // seems to be a touch device
  if(_mouseDetected && !$(this.hover)) {
    _mouseDetected = false;
  }
```

**Comment by istvan-ujjmeszaros** [comment]
Thanks @3diuk!
