### ISSUE TITLE
publish latest version on NPM

### ISSUE THREAD

**Issue by pvnr0082t** [istvan-ujjmeszaros/bootstrap-dropdown-hover#16]
Hi @istvan-ujjmeszaros ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and we want to host the library.
I found that the latest version on GitHub is `v1.0.4` but on NPM is `v1.0.0`. Could you please publish the latest versions on npm to make it consistent? Thank you.

https://github.com/cdnjs/cdnjs/issues/9151

**Comment by istvan-ujjmeszaros** [comment]
Hi, sorry for the unresponsiveness for that long time. It is up on npm with the latest version (`v4.0.0`).
