### ISSUE TITLE
plugin breaks after mouseover on dropdown items

### ISSUE THREAD

**Issue by nskpavani** [istvan-ujjmeszaros/bootstrap-dropdown-hover#18]
Hi,

First of all. Excellent work. I did all the steps mentioned. However, I am having an issue with it. When I go through the dropdown first time it works fine. But when the mouse goes over the list item, the plugin stops working. I looked at console but it has no errors. If I refresh the page it works again.

Please help me
nskp

**Comment by istvan-ujjmeszaros** [comment]
Did you try it with Bootstrap 3 or 4? Can you check if it is the same with the latest version of the plugin? If yes, then please specify your browser.

**Comment by istvan-ujjmeszaros** [comment]
I am closing it for now, please reopen with an example code if it is the same with the latest version.

**Comment by nskpavani** [comment]
Sorry didn't see your reply....i totally forgot the issue as it was 12 months ago...anyways I did solve it with a script myself. 

-Nskp
