### ISSUE TITLE
Doesn't support explicit target

### ISSUE THREAD

**Issue by hkmaly** [istvan-ujjmeszaros/bootstrap-dropdown-hover#19]
For bootstrap dropdown, the target element selector can be specified in target data attribute ; the parent of dropdown-toggle is just fallback. This library only supports the parent.

**Comment by istvan-ujjmeszaros** [comment]
If you doesn't specify a selector, then it will be instantiated on every element that has `data-toggle="dropdown"` specified. But you can instantiate the plugin with a selector, like `$('.navbar [data-toggle="dropdown"]').bootstrapDropdownHover();` or like `$('#navbartoggle').bootstrapDropdownHover();` if there is this id set on the toggle.

**Comment by hkmaly** [comment]
I'm talking about target of the dropdown. By default, when you click the dropdown, the parent of dropdown is made active, which displays the dropdown. But this behaviour can be changed by explicitly specifying the data-target of the dropdown element.

```
<a href="http://example.com/" data-toggle="dropdown" data-target=".navbar .about" class="dropdown-toggle">
```

**Comment by hkmaly** [comment]
Hello,
any progress on it? I updated the pull request, did you noticed? Or should I make new one?

**Comment by istvan-ujjmeszaros** [comment]
Actually it doesn't seem to work. I have tried to fix it based on your pull request back then and didn't have time to do it, just getting back to it.

**Comment by istvan-ujjmeszaros** [comment]
If you could add a working demo to at least one of the demo html files inside the demo folder (FYI one is for bs3, the other is for bs4) then it would be great. I can build the dist versions and can merge your pull request then.
Feel free to close the current pull request and add a new one if it is easier.

**Comment by istvan-ujjmeszaros** [comment]
FYI the demo you have added works even if I don't update the plugin javascript code with your modifications, but doesn't work if I remove the `dropdown-toggle` class from the dropdown toggle element, and I think the point of your updates would be that it should work without that class specified. Or did I misunderstood something?
Anyway I am giving it an other go so you may wait a bit, hopefully I can make it work soon with fewer changes to the code.

**Comment by istvan-ujjmeszaros** [comment]
Sorry, I was confused with the different changes :) It seems to work fine, the only minor issue (although I am not 100% sure that this is an issue) is that `data-toggle` class must present on the toggle.
