### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by JakeDixon** [istvan-ujjmeszaros/bootstrap-dropdown-hover#3]
Hi, 

I have downloaded and loaded the JS

jquery.bootstrap-dropdown-hover.min.js

and call the jQuery.fn.bootstrapDropdownHover({}); method but the menus arn't dropping down on hover. 

can you offer any advice? 

Versions
Bootstrap 3.3.5
Plugin 1.0.4

**Comment by istvan-ujjmeszaros** [comment]
Do you see any error messages in your browsers console?
Can you link your page where I can see the issue?

**Comment by JakeDixon** [comment]
Hi, no errors in my console, I'm confident it's probably me doing something wrong but not sure what.

http://www.tjdixon.com/?template=tjdixon-bootstrap3.3.5 

Thanks.

**Comment by istvan-ujjmeszaros** [comment]
Please take a look on the bootstrap navbar example and correct your markup according to that:
http://getbootstrap.com/components/#navbar

Something like that will work:

``` html
<li class="dropdown">
  <a href="/services" class="dropdown-toggle" data-toggle="dropdown">Services <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="/link1">submenu1</a></li>
    <li><a href="/link2">submenu2</a></li>
    <li><a href="/link3">submenu3</a></li>
  </ul>
</li>
```

**Comment by JakeDixon** [comment]
Thank you, it was exactly that. :+1: Awesome work!
