### ISSUE TITLE
Stuck on 1.

### ISSUE THREAD

**Issue by FiroStefani** [istvan-ujjmeszaros/bootstrap-dropdown-hover#5]
All four steps of the installation process and two alternative initialization calls are numbered 1.

**Comment by istvan-ujjmeszaros** [comment]
What do you mean? Please explain the issue.

**Comment by FiroStefani** [comment]
I’m sorry if I was unclear István. The attached screenshot should clarify this very minor issue. I have not much familiarly with GitHub so perhaps it was not the appropriate place for things like this. 

Your code is working very well for me, though it seems the even with clickBehavior: ‘disable’ the hover state persists after the mouse moves off. Sometimes. It seems to work as I expect when I have the Chrome debugging window open! 

Test case source follows, thanks for your great work! 

<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<script src="../bower_components/jquery/dist/jquery.min.js"></script>

<script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="../bower_components/bootstrap-dropdown-hover/dist/jquery.bootstrap-dropdown-hover.min.js"></script>

<title>Bootstrap dropdown</title>

<style type="text/css">
.btn-xs {
               color: #00C; 
}
</style>

</head>
<body>
<div class="btn-group">
               <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">Mescaline</button>
               <ul class="dropdown-menu">
                              <li><img src="C/pk51.png" alt="Mescaline" title="Mescaline"></li>
                              <li role="separator" class="divider"></li>
                              <li><a href="read.php?domain=pk&amp;id=51">Read about Mescaline</a></li>
                              <li><a href="explore.php?domain=pk&amp;id=51">Explore Mescaline</a></li>
                              <li><a href="search.php?domain=pk&amp;id=51">Search for Mescaline</a></li>
               </ul>
</div> is one of the oldest psychedelics known to man. It is the major active component of the small dumpling cactus known as Peyote.  

<script type="application/javascript">
$.fn.bootstrapDropdownHover({
     clickBehavior: "disable"
});
</script>

</body>
</html>

**Comment by istvan-ujjmeszaros** [comment]
I don't see the issue but I will double check the event handlers.
Can you try if it is the same if you use an `a` tag instead of the `button`?

Something like that:

``` html
<a href="#" class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">Mescaline</a>
```

**Comment by FiroStefani** [comment]
That works perfectly, thank you!
